### ISSUE TITLE
usan warning:

### ISSUE THREAD

**Issue by etorth** [kimwalisch/libpopcnt#13]
in function: static inline uint64_t popcnt64_unrolled(const uint64_t* data, uint64_t size), USAN reports warning:

libpopcnt.h:229:20: runtime error: load of misaligned address 0x7fffcfe2d001 for type 'const uint64_t', which requires 8 byte alignment
0x7fffcfe2d001: note: pointer points here
 7f 00 00  0a 0f 00 00 00 00 00 00  00 3f 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 74 65 73 74
              ^

**Comment by etorth** [comment]
I am calling: static inline uint64_t popcnt(const void* data, uint64_t size)
seems internally it redirect to popcnt64_unrolled and reports the misalign issue.

**Comment by kimwalisch** [comment]
I know about this particular **load of misaligned address** and it is actually intentional. All x86 CPUs support unaligned memory accesses, so I took advantage of that and removed the alignment code on x86 to improve performance.

Is that OK for you?

**Comment by etorth** [comment]
thanks for the comment!
