### ISSUE TITLE
consider making this CPM compliant

### ISSUE THREAD

**Issue by andersfylling** [kimwalisch/libpopcnt#14]
https://github.com/TheLartians/CPM.cmake

It allows developers to include your project by simply adding the following to their CMakeLists.tzt
```CMake
CPMAddPackage(
        NAME libpopcnt
        GITHUB_REPOSITORY kimwalisch/libpopcnt
        VERSION 2.3
)
target_link_libraries(MyProgram PUBLIC libpopcnt)
```

**Comment by kimwalisch** [comment]
I might support CPM once it is widely used or there is an important project using libpopcnt which requires this feature.
