### ISSUE TITLE
Overwriting value of abcd returned by __cpuidex for MSVC

### ISSUE THREAD

**Issue by KOConchobhair** [kimwalisch/libpopcnt#4]
Doesn't this line of code overwrite the value returned by __cpuidex when using MSVC?

https://github.com/kimwalisch/libpopcnt/blob/92f8a3401ec24f4897fe49086306cdcb170a323d/libpopcnt.h#L249

**Comment by kimwalisch** [comment]
I think you are right, according to [MSDN](https://msdn.microsoft.com/en-us/library/hskdteyh.aspx) ```__cpuidex``` will populate the ```abcd[4]``` array with the values of eax, ebx, ecx and edx.

Hence my code:

```C++
  __cpuidex(abcd, eax, ecx);

  abcd[0] = eax;
  abcd[1] = ebx;
  abcd[2] = ecx;
  abcd[3] = edx;
```

is not needed for MSVC and actually overwrites the correct values inside the ```abcd[4]``` array with incorrect values (eax, ebx, ecx, edx). I will fix this bug tomorrow.

Thanks!

**Comment by kimwalisch** [comment]
Fixed by commit: https://github.com/kimwalisch/libpopcnt/commit/c5d90e019e9562e509e42ba98676e4d9b9b2a87b
